version: '3.8'
services:
  app:
    build: ./app
    restart: always
    env_file:
      - .env
    hostname: app
    volumes:
      - .:/app
      - /app/node_modules
    command: yarn run start:prod
    ports:
      - 4000:4000
